name: denbi
channels:
  - pytorch
  - nvidia
  - anaconda
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - appdirs=1.4.4=pyhd3eb1b0_0
  - asttokens=2.0.5=pyhd3eb1b0_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - blas=1.0=mkl
  - bottleneck=1.3.5=py310ha9d4c09_0
  - brotlipy=0.7.0=py310h7f8727e_1002
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2023.01.10=h06a4308_0
  - certifi=2022.12.7=py310h06a4308_0
  - cffi=1.15.1=py310h5eee18b_3
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - click=8.0.4=py310h06a4308_0
  - comm=0.1.2=py310h06a4308_0
  - cryptography=38.0.4=py310h9ce1e76_0
  - cuda-cudart=11.8.89=0
  - cuda-cupti=11.8.87=0
  - cuda-libraries=11.8.0=0
  - cuda-nvrtc=11.8.89=0
  - cuda-nvtx=11.8.86=0
  - cuda-runtime=11.8.0=0
  - debugpy=1.5.1=py310h295c915_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - docker-pycreds=0.4.0=pyhd3eb1b0_0
  - einops=0.6.0=pyhd8ed1ab_0
  - entrypoints=0.4=py310h06a4308_0
  - et_xmlfile=1.1.0=py310h06a4308_0
  - executing=0.8.3=pyhd3eb1b0_0
  - ffmpeg=4.3=hf484d3e_0
  - filelock=3.9.0=py310h06a4308_0
  - flit-core=3.6.0=pyhd3eb1b0_0
  - freetype=2.12.1=h4a9f257_0
  - fsspec=2022.11.0=py310h06a4308_0
  - giflib=5.2.1=h5eee18b_1
  - gitdb=4.0.7=pyhd3eb1b0_0
  - gitpython=3.1.30=py310h06a4308_0
  - gmp=6.2.1=h295c915_3
  - gmpy2=2.1.2=py310heeb90bb_0
  - gnutls=3.6.15=he1e5248_0
  - h5py=3.7.0=py310he06866b_0
  - hdf5=1.10.6=h3ffc7dd_1
  - idna=3.4=py310h06a4308_0
  - intel-openmp=2022.1.0=h9e868ea_3769
  - ipykernel=6.19.2=py310h2f386ee_0
  - ipython=8.8.0=py310h06a4308_0
  - jedi=0.18.1=py310h06a4308_1
  - jinja2=3.1.2=py310h06a4308_0
  - joblib=1.1.1=py310h06a4308_0
  - jpeg=9e=h7f8727e_0
  - jupyter_client=7.4.8=py310h06a4308_0
  - jupyter_core=5.1.1=py310h06a4308_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libblas=3.9.0=16_linux64_mkl
  - libcblas=3.9.0=16_linux64_mkl
  - libcublas=11.11.3.6=0
  - libcufft=10.9.0.58=0
  - libcufile=1.6.0.25=0
  - libcurand=10.3.2.56=0
  - libcusolver=11.4.1.48=0
  - libcusparse=11.7.5.86=0
  - libdeflate=1.8=h7f8727e_5
  - libffi=3.4.2=h6a678d5_6
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h7f8727e_2
  - libidn2=2.3.2=h7f8727e_0
  - liblapack=3.9.0=16_linux64_mkl
  - libnpp=11.8.0.86=0
  - libnvjpeg=11.9.0.86=0
  - libpng=1.6.37=hbc83047_0
  - libprotobuf=3.20.3=he621ea3_0
  - libsodium=1.0.18=h7b6447c_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.16.0=h27cfd23_0
  - libtiff=4.5.0=h6a678d5_1
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp=1.2.4=h11a3e52_0
  - libwebp-base=1.2.4=h5eee18b_0
  - lightning-utilities=0.8.0=pyhd8ed1ab_0
  - lz4-c=1.9.4=h6a678d5_0
  - markupsafe=2.1.1=py310h7f8727e_0
  - matplotlib-inline=0.1.6=py310h06a4308_0
  - mkl=2022.1.0=hc2b9512_224
  - mpc=1.1.0=h10f8cd9_1
  - mpfr=4.0.2=hb69a4c5_1
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.5.6=py310h06a4308_0
  - nettle=3.7.3=hbbd107a_1
  - networkx=2.8.4=py310h06a4308_0
  - nomkl=2.0=0
  - numexpr=2.8.0=py310hf05e7a9_102
  - numpy=1.22.3=py310h4ef5377_2
  - openh264=2.1.1=h4ff587b_0
  - openpyxl=3.0.10=py310h5eee18b_0
  - openssl=1.1.1s=h7f8727e_0
  - packaging=22.0=py310h06a4308_0
  - pandas=1.5.2=py310h1128e8f_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pathtools=0.1.2=pyhd3eb1b0_1
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=9.3.0=py310h6a678d5_2
  - pip=22.3.1=py310h06a4308_0
  - platformdirs=2.5.2=py310h06a4308_0
  - prompt-toolkit=3.0.36=py310h06a4308_0
  - protobuf=3.20.3=py310h6a678d5_0
  - psutil=5.9.0=py310h5eee18b_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.11.2=pyhd3eb1b0_0
  - pyopenssl=22.0.0=pyhd3eb1b0_0
  - pyparsing=3.0.9=py310h06a4308_0
  - pysocks=1.7.1=py310h06a4308_0
  - python=3.10.9=h7a1cb2a_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python_abi=3.10=2_cp310
  - pytorch=2.0.0=py3.10_cuda11.8_cudnn8.7.0_0
  - pytorch-cuda=11.8=h7e8668a_3
  - pytorch-lightning=2.0.1=pyhd8ed1ab_0
  - pytorch-mutex=1.0=cuda
  - pytz=2022.7=py310h06a4308_0
  - pyyaml=6.0=py310h5eee18b_1
  - pyzmq=23.2.0=py310h6a678d5_0
  - readline=8.2=h5eee18b_0
  - requests=2.28.1=py310h06a4308_0
  - scikit-learn=1.2.0=py310h6a678d5_1
  - scipy=1.8.1=py310h7612f91_0
  - sentry-sdk=1.9.0=py310h06a4308_0
  - setproctitle=1.2.2=py310h7f8727e_0
  - setuptools=65.6.3=py310h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - smmap=4.0.0=pyhd3eb1b0_0
  - sqlite=3.40.1=h5082296_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - sympy=1.11.1=py310h06a4308_0
  - threadpoolctl=2.2.0=pyh0d69192_0
  - tk=8.6.12=h1ccaba5_0
  - torchinfo=1.7.2=pyhd8ed1ab_0
  - torchmetrics=0.11.4=pyhd8ed1ab_0
  - torchtriton=2.0.0=py310
  - torchvision=0.15.0=py310_cu118
  - tornado=6.2=py310h5eee18b_0
  - tqdm=4.64.1=py310h06a4308_0
  - traitlets=5.7.1=py310h06a4308_0
  - typing_extensions=4.4.0=py310h06a4308_0
  - tzdata=2022a=hda174b7_0
  - urllib3=1.26.14=py310h06a4308_0
  - wandb=0.14.1=pyhd8ed1ab_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - xz=5.2.10=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - yapf=0.31.0=pyhd3eb1b0_0
  - zeromq=4.3.4=h2531618_0
  - zlib=1.2.13=h5eee18b_0
  - zstd=1.5.2=ha4553b6_0
  - pip:
    - dgl==1.0.1
    - mpmath==1.2.1
prefix: /home/ubuntu/Miniconda3-py39_4.12.0-Linux-x86_64/envs/denbi
